/**
 * Build the single-file `axis` binaries: CLI, hub, daemon, MCP server, hook,
 * tree-sitter grammars and the dashboard, all in one executable per platform.
 *
 *   bun scripts/build.ts                 every release target
 *   bun scripts/build.ts --host          just this machine (fast, for local testing)
 *
 * Output: dist/bin/axis-<os>-<arch> plus SHA256SUMS.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const TARGETS = ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"] as const;
const hostOnly = process.argv.includes("--host");
const targets = hostOnly ? [`${process.platform}-${process.arch}`] : [...TARGETS];

const dashDist = path.join(root, "dashboard/dist");
if (!existsSync(path.join(dashDist, "index.html"))) {
  console.error("dashboard/dist is missing: run `bun run build:dashboard` first.");
  process.exit(1);
}

// An entry that embeds every dashboard file (Bun copies `type: "file"` imports into the executable)
// and hands the map to `axis hub` before the CLI starts.
const buildDir = path.join(root, "dist/build");
rmSync(buildDir, { recursive: true, force: true });
mkdirSync(buildDir, { recursive: true });
const files: string[] = [];
const walk = (d: string) => {
  for (const name of readdirSync(d)) {
    const abs = path.join(d, name);
    if (statSync(abs).isDirectory()) walk(abs);
    else files.push(path.relative(dashDist, abs).split(path.sep).join("/"));
  }
};
walk(dashDist);
const rel = (f: string) =>
  path.relative(buildDir, path.join(dashDist, f)).split(path.sep).join("/");
writeFileSync(
  path.join(buildDir, "entry.ts"),
  `// Generated by scripts/build.ts.\n${files.map((f, i) => `import f${i} from ${JSON.stringify(rel(f))} with { type: "file" };`).join("\n")}\n` +
    `(globalThis as { __AXIS_DASHBOARD__?: Map<string, string> }).__AXIS_DASHBOARD__ = new Map([${files.map((f, i) => `[${JSON.stringify(f)}, f${i}]`).join(", ")}]);\n` +
    `await import(${JSON.stringify(path.relative(buildDir, path.join(root, "src/cli/main.ts")).split(path.sep).join("/"))});\n`
);

const outDir = path.join(root, "dist/bin");
mkdirSync(outDir, { recursive: true });
const sums: string[] = [];
for (const target of targets) {
  const out = path.join(outDir, `axis-${target}`);
  const p = Bun.spawnSync(
    [
      "bun",
      "build",
      path.join(buildDir, "entry.ts"),
      "--compile",
      "--minify",
      `--target=bun-${target}`,
      "--outfile",
      out,
    ],
    { cwd: root, stdout: "inherit", stderr: "inherit" }
  );
  if (p.exitCode !== 0) process.exit(p.exitCode ?? 1);
  const sha = createHash("sha256").update(readFileSync(out)).digest("hex");
  sums.push(`${sha}  axis-${target}`);
  console.log(`dist/bin/axis-${target}  ${(statSync(out).size / 1e6).toFixed(1)} MB`);
}
writeFileSync(path.join(outDir, "SHA256SUMS"), sums.join("\n") + "\n");
